/*
 * Automatically generated by make menuconfig: don't edit
 */
#define AUTOCONF_INCLUDED

/*
 * Target Platform Selection
 */
#define CONFIG_DEFAULTS_WINBOND_W90N745 1
#define CONFIG_DEFAULTS_KERNEL_2_4 1
#undef  CONFIG_DEFAULTS_OVERRIDE
#define CONFIG_DEFAULTS_KERNEL 1
#undef  CONFIG_DEFAULTS_VENDOR
#undef  CONFIG_DEFAULTS_VENDOR_UPDATE
