#!/usr/bin/perl

# $RCSfile: ADB,v $$Revision: 1.1.1.1 $$Date: 2006-07-11 09:31:43 $

# This script is only useful when used in your crash directory.

$num = shift;
exec 'adb', '-k', "vmunix.$num", "vmcore.$num";
