
.EXPORT_ALL_VARIABLES:

EXTRA_CFLAGS += -I$(ROOTDIR)/freeswan/lib
EXTRA_CFLAGS += -I$(ROOTDIR)/freeswan/klips/net/ipsec

VPATH = $(ROOTDIR)/freeswan/lib

include $(ROOTDIR)/freeswan/lib/Makefile.kernel

