#define UTS_VERSION "#450 Tue Jul 10 17:43:53 CST 2012"
#define LINUX_COMPILE_TIME "17:43:53"
#define LINUX_COMPILE_BY "root"
#define LINUX_COMPILE_HOST "embedded"
#define LINUX_COMPILE_DOMAIN "localdomain"
#define LINUX_COMPILER "gcc version 3.0"
