#
# libposix makefile
# $Id: Makefile,v 1.1.1.1 2006-08-14 02:32:36 andy Exp $
#

ARCHFLAGS = 

SRCS = libposix.c
OBJS = libposix.o

CFLAGS = -O -D_POSIX_SOURCE $(ARCHFLAGS)

all: $(OBJS)

clean:
	rm -f *.o *~ core

