# This is the kernel makefile, it is not used when compiling modules outside
# the kernel tree.

O_TARGET := ffs2.o
O_OBJS   := super.o io.o
MI_OBJS   := $(O_TARGET)
	    
include $(TOPDIR)/Rules.make
	    
