#	$Id: Makefile.bsd,v 1.1.1.1 2006-07-11 09:32:10 andy Exp $

PROG=	pppstats
SRCS=	pppstats.c
CFLAGS+=-I../include -D_BITYPES
MAN8=	pppstats.8
MAN=	pppstats.cat8
BINDIR=	/usr/sbin

.include <bsd.prog.mk>
