#
# pppstats Makefile for SVR4 systems
# $Id: Makefile.sol2,v 1.1.1.1 2006-07-11 09:32:10 andy Exp $
#

include ../svr4/Makedefs

CFLAGS = -DSTREAMS -I../include $(COPTS)

all: pppstats

pppstats: pppstats.c
	$(CC) $(CFLAGS) -o pppstats pppstats.c

install: pppstats
	$(INSTALL) -f $(BINDIR) pppstats
	$(INSTALL) -m 444 -f $(MANDIR)/man8 pppstats.8

clean:
	rm -f pppstats *~ core
