#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile.ssl for crypto/cversion.c */
  #define CFLAGS "gcc -DOPENSSL_NO_KRB5 -DOPENSSL_NO_ENGINE -DOPENSSL_NO_HW -DOPENSSL_NO_ASM -DL_ENDIAN -DTERMIO -O3 -fomit-frame-pointer -m486 -Wall"
  #define PLATFORM "linux-elf"
  #define DATE "Tue Feb 17 11:41:24 CST 2004"
#endif
