/*  DO NOT EDIT THIS FILE.

    It has been auto-edited by fixincludes from:

	"/Temp/make-compile/arm_tools_3.3.4/arm-elf/include/asm-armnommu/arch-W90P710/cdefs.h"

    This had to be done to correct non-standard usages in the
    original, manufacturer supplied header file.  */

#ifndef CDEFS_H
#define CDEFS_H

#define AHBBASE	0xFFF00000
#define FLASH_BASE	(0x7F000000)
#define ROMCON	(AHBBASE + 0x1004)
#define W90P710_FLASH_SIZE	(0x40000<<(( *((UINT *)ROMCON)>>16 )&0x7))
#define FLASH_BLOCK_SIZE	(0x10000)
#define FLASH_SIZE	(W90P710_FLASH_SIZE)
//------------------------------------------------------------------------------
#define UINT16	u16
typedef int INT;
typedef int SIGNED;
typedef unsigned int UNSIGNED;
typedef unsigned int UINT;
typedef unsigned int UINT32;
typedef unsigned char UCHAR;
typedef char CHAR;
typedef void VOID;
typedef unsigned long ULONG;
#ifndef NULL
#define NULL	0
#endif

//------------------------------------------------------------------------------
#endif
