#
# linux/drivers/maps/Makefile.24
# Makefile for obsolete kernels
#
# $Id: Makefile,v 1.1.1.1 2006-07-11 09:29:05 andy Exp $

O_TARGET	:= mapslink.o
export-objs	:= map_funcs.o

include Makefile.common
include $(TOPDIR)/Rules.make
