#
# linux/drivers/chips/Makefile.24
# Makefile for obsolete kernels.
#
# $Id: Makefile,v 1.1.1.1 2006-07-11 09:29:06 andy Exp $

O_TARGET	:= chipslink.o
export-objs	:= chipreg.o gen_probe.o cfi_util.o

include Makefile.common

include $(TOPDIR)/Rules.make
