"Xmppp*background: gray65",
"Xmppp*foreground: black",
"Xmppp*highlightColor: Red",
"Xmppp*indicator.width: 20",
"Xmppp*indicator.height: 10",
"Xmppp*highlightThickness: 1",
"Xmppp*menubarw*fontList: *helvetica-medium-r-normal--12*",
"Xmppp*XmPushButton.fontList: *helvetica-medium-r-normal--12*",
"Xmppp*XmPushButtonGadget.fontList: *helvetica-medium-r-normal--12*",
"Xmppp*XmLabel.fontList: *helvetica-medium-r-normal--12*",
"Xmppp*XmLabelGadget.fontList: *helvetica-medium-r-normal--12*",
"Xmppp*XmToggleButton.fontList: *helvetica-medium-r-normal--12*",
"Xmppp*XmPushButton.marginLeft: 4",
"Xmppp*XmPushButton.marginRight: 4",
"Xmppp*XmPushButton.marginTop: 4",
"Xmppp*XmPushButton.marginBottom: 4",
"Xmppp*tframew.background: black",
"Xmppp*tframew.foreground: black",
"Xmppp*bformw.background: black",
"Xmppp*XmScrollBar*width: 16",
"Xmppp*XmScrollBar*height: 16",
"Xmppp*pppb.labelString: Connect",
"Xmppp*dlabw.labelString: Dialing Status",
"Xmppp*debugtextw.background: white",
"Xmppp*debugtextw.fontList: fixed",
"Xmppp*debugtextw.rows: 14",
"Xmppp*debugtextw.columns: 65",
"Xmppp*namelab.labelString: X mppp version 1.1b",
"Xmppp*namelab.background: black",
"Xmppp*namelab.foreground: white",
"Xmppp*timerw.background: black",
"Xmppp*timerw.foreground: white",
"Xmppp*timerw.labelString: 00:00:00",
"Xmppp*counterlabw.background: black",
"Xmppp*counterlabw.foreground: green",
"Xmppp*counterlabw.labelString: 00:00:00",
"Xmppp*aboutdw.dialogTitle: About X mppp",
"Xmppp*aboutdw.messageAlignment: alignment_center",
"Xmppp*aboutdw*fontList: lucidasans-12,lucidasans-bold-12=BOLD,*helvetica-bold-r-*-140*=BIG,lucidasans-10=SMALL,lucidasans-italic-12=ITALIC",
"Xmppp*aboutdw.messageString:\
<BIG>Xmppp Release 1.1b<>\\n\
<SMALL>[ Jun-8-1997, A vacation hack! ]<>\\n\
\\n\
X mppp - A PPP dialer in Motif\\n\
By\\n\
Muhammad A. Muquit\\n\
\\n\
http://www.fccc.edu/users/muquit/\\n\
<BOLD>Email: <SMALL>ma_muquit@fccc.edu",
"Xmppp*askuserd.dialogTitle: Kill pppd?",
"Xmppp*askuserd*messageAlignment: alignment_center",
"Xmppp*askuserd*fontList: *helvetica-bold-r-*-140*",
"Xmppp*askuserd.okLabelString: Kill and Quit",
"Xmppp*askuserd.cancelLabelString: Quit Without Killing",
"Xmppp*askuserd.helpLabelString: I Changed my mind",
"Xmppp*filemenu.mnemonic: F",
"Xmppp*filemenu.quit.accelerator: Meta<Key>q",
"Xmppp*filemenu.quit.acceleratorText: Alt+Q ",
"Xmppp*optionsmenu.mnemonic: O",
"Xmppp*optionsmenu.editc.accelerator: Meta<Key>e",
"Xmppp*optionsmenu.editc.acceleratorText: Alt+E",
"Xmppp*helpmenu.mnemonic: H",
"Xmppp*helpmenu.about.accelerator: Meta<Key>a",
"Xmppp*helpmenu.about.acceleratorText: Alt+A",
