
all clean:

romfs:
	$(ROMFSINST) -e CONFIG_USER_RAMIMAGE_RAMFS64  ramfs64.img  /etc/ramfs.img
	$(ROMFSINST) -e CONFIG_USER_RAMIMAGE_RAMFS128 ramfs128.img /etc/ramfs.img
	$(ROMFSINST) -e CONFIG_USER_RAMIMAGE_RAMFS256 ramfs256.img /etc/ramfs.img
	$(ROMFSINST) -e CONFIG_USER_RAMIMAGE_RAMFS512 ramfs512.img /etc/ramfs.img

